/*
 * Copyright (c) 2026 Sascha G. Eurich, Melowsyne UNIPESSOAL LDA
 * SPDX-License-Identifier: MIT
 */

/* GENERATED by fountain_proto_schema/generate.py — DO NOT EDIT.
 * Source: fountain_proto_schema/schema.py */

#include "fountain_msgs.h"
#include <string.h>

static const fp_msg_meta_t s_meta[FP_MSG_COUNT] = {
    { FP_MSG_HELLO, "hello", FP_DIR_C2S, FP_AUTH_NONE, 1, true, FP_MSG_HELLO_ACK },
    { FP_MSG_HELLO_ACK, "hello_ack", FP_DIR_S2C, FP_AUTH_NONE, 1, false, FP_MSG_COUNT },
    { FP_MSG_PROTOCOL_MISMATCH, "protocol_mismatch", FP_DIR_C2S, FP_AUTH_NONE, 1, false, FP_MSG_COUNT },
    { FP_MSG_OTA_CHECK, "ota_check", FP_DIR_C2S, FP_AUTH_SESSION, 2, true, FP_MSG_OTA_AVAILABLE },
    { FP_MSG_OTA_AVAILABLE, "ota_available", FP_DIR_S2C, FP_AUTH_CONTROL, 2, false, FP_MSG_OTA_STATUS },
    { FP_MSG_OTA_NONE, "ota_none", FP_DIR_S2C, FP_AUTH_NONE, 2, false, FP_MSG_COUNT },
    { FP_MSG_OTA_CANCEL, "ota_cancel", FP_DIR_S2C, FP_AUTH_CONTROL, 2, false, FP_MSG_OTA_STATUS },
    { FP_MSG_OTA_STATUS, "ota_status", FP_DIR_C2S, FP_AUTH_NONE, 2, false, FP_MSG_COUNT },
    { FP_MSG_HEARTBEAT, "heartbeat", FP_DIR_C2S, FP_AUTH_NONE, 2, false, FP_MSG_COUNT },
    { FP_MSG_DP_REPORT, "dp_report", FP_DIR_C2S, FP_AUTH_NONE, 2, false, FP_MSG_COUNT },
    { FP_MSG_DP_READ, "dp_read", FP_DIR_S2C, FP_AUTH_NONE, 2, true, FP_MSG_DP_REPORT },
    { FP_MSG_DP_WRITE, "dp_write", FP_DIR_S2C, FP_AUTH_CONTROL, 2, true, FP_MSG_DP_WRITE_RESULT },
    { FP_MSG_DP_WRITE_RESULT, "dp_write_result", FP_DIR_C2S, FP_AUTH_NONE, 2, false, FP_MSG_COUNT },
    { FP_MSG_COMMAND, "command", FP_DIR_S2C, FP_AUTH_CONTROL, 2, true, FP_MSG_COMMAND_RESULT },
    { FP_MSG_COMMAND_RESULT, "command_result", FP_DIR_C2S, FP_AUTH_NONE, 2, false, FP_MSG_COUNT },
    { FP_MSG_ERROR_REPORT, "error_report", FP_DIR_C2S, FP_AUTH_NONE, 2, false, FP_MSG_COUNT },
    { FP_MSG_DEVICE_ALERT, "device_alert", FP_DIR_C2S, FP_AUTH_NONE, 2, false, FP_MSG_COUNT },
    { FP_MSG_LOG_READ, "log_read", FP_DIR_S2C, FP_AUTH_CONTROL, 2, true, FP_MSG_LOG_BATCH },
    { FP_MSG_LOG_BATCH, "log_batch", FP_DIR_C2S, FP_AUTH_NONE, 2, false, FP_MSG_COUNT },
    { FP_MSG_LOG_READ_PREV, "log_read_prev", FP_DIR_S2C, FP_AUTH_CONTROL, 2, true, FP_MSG_LOG_BATCH },
    { FP_MSG_LOG_ACK_PREV, "log_ack_prev", FP_DIR_S2C, FP_AUTH_CONTROL, 2, true, FP_MSG_LOG_ACK_RESULT },
    { FP_MSG_LOG_ACK_RESULT, "log_ack_result", FP_DIR_C2S, FP_AUTH_NONE, 2, false, FP_MSG_COUNT },
    { FP_MSG_HISTORY_READ, "history_read", FP_DIR_S2C, FP_AUTH_CONTROL, 2, true, FP_MSG_HISTORY_BATCH },
    { FP_MSG_HISTORY_BATCH, "history_batch", FP_DIR_C2S, FP_AUTH_NONE, 2, false, FP_MSG_COUNT },
};

const char *fp_msg_type_name(fp_msg_type_t t) {
    return (t < FP_MSG_COUNT) ? s_meta[t].name : "?";
}

fp_msg_type_t fp_msg_type_from_name(const char *name) {
    for (int i = 0; i < FP_MSG_COUNT; i++)
        if (strcmp(s_meta[i].name, name) == 0) return (fp_msg_type_t)i;
    return FP_MSG_COUNT;
}

const fp_msg_meta_t *fp_msg_meta(fp_msg_type_t t) {
    return (t < FP_MSG_COUNT) ? &s_meta[t] : NULL;
}

cJSON *fp_hello_build(const fp_hello_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddStringToObject(o, "device_id", m->device_id);
    cJSON_AddNumberToObject(o, "protocol_version", (double)m->protocol_version);
    cJSON_AddStringToObject(o, "fw_version", m->fw_version);
    if (m->has_hw_rev) cJSON_AddStringToObject(o, "hw_rev", m->hw_rev);
    if (m->has_boot_reason) cJSON_AddStringToObject(o, "boot_reason", m->boot_reason);
    if (m->auth_schemes) cJSON_AddItemToObject(o, "auth_schemes", cJSON_Duplicate(m->auth_schemes, 1));
    if (m->auth_kids) cJSON_AddItemToObject(o, "auth_kids", cJSON_Duplicate(m->auth_kids, 1));
    if (m->has_client_nonce) cJSON_AddStringToObject(o, "client_nonce", m->client_nonce);
    return o;
}

bool fp_hello_parse(const cJSON *root, fp_hello_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "device_id");
    if (cJSON_IsString(it)) { out->device_id = it->valuestring; out->has_device_id = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "protocol_version");
    if (cJSON_IsNumber(it)) { out->protocol_version = (uint8_t)it->valuedouble; out->has_protocol_version = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "fw_version");
    if (cJSON_IsString(it)) { out->fw_version = it->valuestring; out->has_fw_version = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "hw_rev");
    if (cJSON_IsString(it)) { out->hw_rev = it->valuestring; out->has_hw_rev = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "boot_reason");
    if (cJSON_IsString(it)) { out->boot_reason = it->valuestring; out->has_boot_reason = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "auth_schemes");
    if ((it != NULL)) { out->auth_schemes = (cJSON *)it; out->has_auth_schemes = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "auth_kids");
    if ((it != NULL)) { out->auth_kids = (cJSON *)it; out->has_auth_kids = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "client_nonce");
    if (cJSON_IsString(it)) { out->client_nonce = it->valuestring; out->has_client_nonce = true; }
    return true;
}

cJSON *fp_hello_ack_build(const fp_hello_ack_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddBoolToObject(o, "accepted", m->accepted);
    if (m->supported_protocols) cJSON_AddItemToObject(o, "supported_protocols", cJSON_Duplicate(m->supported_protocols, 1));
    cJSON_AddNumberToObject(o, "server_ts", (double)m->server_ts);
    if (m->has_reason) cJSON_AddStringToObject(o, "reason", m->reason);
    if (m->has_auth_required) cJSON_AddBoolToObject(o, "auth_required", m->auth_required);
    if (m->has_auth_scheme) cJSON_AddStringToObject(o, "auth_scheme", m->auth_scheme);
    if (m->has_auth_scope) cJSON_AddStringToObject(o, "auth_scope", m->auth_scope);
    if (m->has_auth_kid) cJSON_AddStringToObject(o, "auth_kid", m->auth_kid);
    if (m->has_server_nonce) cJSON_AddStringToObject(o, "server_nonce", m->server_nonce);
    return o;
}

bool fp_hello_ack_parse(const cJSON *root, fp_hello_ack_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "accepted");
    if (cJSON_IsBool(it)) { out->accepted = cJSON_IsTrue(it); out->has_accepted = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "supported_protocols");
    if ((it != NULL)) { out->supported_protocols = (cJSON *)it; out->has_supported_protocols = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "server_ts");
    if (cJSON_IsNumber(it)) { out->server_ts = (int64_t)it->valuedouble; out->has_server_ts = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "reason");
    if (cJSON_IsString(it)) { out->reason = it->valuestring; out->has_reason = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "auth_required");
    if (cJSON_IsBool(it)) { out->auth_required = cJSON_IsTrue(it); out->has_auth_required = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "auth_scheme");
    if (cJSON_IsString(it)) { out->auth_scheme = it->valuestring; out->has_auth_scheme = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "auth_scope");
    if (cJSON_IsString(it)) { out->auth_scope = it->valuestring; out->has_auth_scope = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "auth_kid");
    if (cJSON_IsString(it)) { out->auth_kid = it->valuestring; out->has_auth_kid = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "server_nonce");
    if (cJSON_IsString(it)) { out->server_nonce = it->valuestring; out->has_server_nonce = true; }
    return true;
}

cJSON *fp_protocol_mismatch_build(const fp_protocol_mismatch_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    if (m->device_protocols) cJSON_AddItemToObject(o, "device_protocols", cJSON_Duplicate(m->device_protocols, 1));
    if (m->server_protocols) cJSON_AddItemToObject(o, "server_protocols", cJSON_Duplicate(m->server_protocols, 1));
    cJSON_AddStringToObject(o, "reason", m->reason);
    return o;
}

bool fp_protocol_mismatch_parse(const cJSON *root, fp_protocol_mismatch_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "device_protocols");
    if ((it != NULL)) { out->device_protocols = (cJSON *)it; out->has_device_protocols = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "server_protocols");
    if ((it != NULL)) { out->server_protocols = (cJSON *)it; out->has_server_protocols = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "reason");
    if (cJSON_IsString(it)) { out->reason = it->valuestring; out->has_reason = true; } else return false;
    return true;
}

cJSON *fp_ota_check_build(const fp_ota_check_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddStringToObject(o, "current_version", m->current_version);
    if (m->has_hw_rev) cJSON_AddStringToObject(o, "hw_rev", m->hw_rev);
    return o;
}

bool fp_ota_check_parse(const cJSON *root, fp_ota_check_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "current_version");
    if (cJSON_IsString(it)) { out->current_version = it->valuestring; out->has_current_version = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "hw_rev");
    if (cJSON_IsString(it)) { out->hw_rev = it->valuestring; out->has_hw_rev = true; }
    return true;
}

cJSON *fp_ota_available_build(const fp_ota_available_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddStringToObject(o, "target_version", m->target_version);
    cJSON_AddStringToObject(o, "url", m->url);
    cJSON_AddNumberToObject(o, "size", (double)m->size);
    cJSON_AddNumberToObject(o, "crc32", (double)m->crc32);
    cJSON_AddStringToObject(o, "sha256", m->sha256);
    cJSON_AddBoolToObject(o, "mandatory", m->mandatory);
    if (m->has_max_attempts) cJSON_AddNumberToObject(o, "max_attempts", (double)m->max_attempts);
    return o;
}

bool fp_ota_available_parse(const cJSON *root, fp_ota_available_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "target_version");
    if (cJSON_IsString(it)) { out->target_version = it->valuestring; out->has_target_version = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "url");
    if (cJSON_IsString(it)) { out->url = it->valuestring; out->has_url = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "size");
    if (cJSON_IsNumber(it)) { out->size = (uint32_t)it->valuedouble; out->has_size = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "crc32");
    if (cJSON_IsNumber(it)) { out->crc32 = (uint32_t)it->valuedouble; out->has_crc32 = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "sha256");
    if (cJSON_IsString(it)) { out->sha256 = it->valuestring; out->has_sha256 = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "mandatory");
    if (cJSON_IsBool(it)) { out->mandatory = cJSON_IsTrue(it); out->has_mandatory = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "max_attempts");
    if (cJSON_IsNumber(it)) { out->max_attempts = (uint8_t)it->valuedouble; out->has_max_attempts = true; }
    return true;
}

cJSON *fp_ota_none_build(const fp_ota_none_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    (void)m;
    return o;
}

bool fp_ota_none_parse(const cJSON *root, fp_ota_none_t *out) {
    memset(out, 0, sizeof(*out));
    (void)root;
    return true;
}

cJSON *fp_ota_cancel_build(const fp_ota_cancel_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    if (m->has_reason) cJSON_AddStringToObject(o, "reason", m->reason);
    return o;
}

bool fp_ota_cancel_parse(const cJSON *root, fp_ota_cancel_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "reason");
    if (cJSON_IsString(it)) { out->reason = it->valuestring; out->has_reason = true; }
    return true;
}

cJSON *fp_ota_status_build(const fp_ota_status_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddStringToObject(o, "target_version", m->target_version);
    cJSON_AddStringToObject(o, "state", m->state);
    if (m->has_attempt) cJSON_AddNumberToObject(o, "attempt", (double)m->attempt);
    if (m->has_progress_pct) cJSON_AddNumberToObject(o, "progress_pct", (double)m->progress_pct);
    if (m->has_error) cJSON_AddStringToObject(o, "error", m->error);
    if (m->has_error_detail) cJSON_AddStringToObject(o, "error_detail", m->error_detail);
    return o;
}

bool fp_ota_status_parse(const cJSON *root, fp_ota_status_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "target_version");
    if (cJSON_IsString(it)) { out->target_version = it->valuestring; out->has_target_version = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "state");
    if (cJSON_IsString(it)) { out->state = it->valuestring; out->has_state = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "attempt");
    if (cJSON_IsNumber(it)) { out->attempt = (uint8_t)it->valuedouble; out->has_attempt = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "progress_pct");
    if (cJSON_IsNumber(it)) { out->progress_pct = (uint8_t)it->valuedouble; out->has_progress_pct = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "error");
    if (cJSON_IsString(it)) { out->error = it->valuestring; out->has_error = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "error_detail");
    if (cJSON_IsString(it)) { out->error_detail = it->valuestring; out->has_error_detail = true; }
    return true;
}

cJSON *fp_heartbeat_build(const fp_heartbeat_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddNumberToObject(o, "uptime_s", (double)m->uptime_s);
    cJSON_AddStringToObject(o, "fw_version", m->fw_version);
    if (m->has_fault_active) cJSON_AddBoolToObject(o, "fault_active", m->fault_active);
    return o;
}

bool fp_heartbeat_parse(const cJSON *root, fp_heartbeat_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "uptime_s");
    if (cJSON_IsNumber(it)) { out->uptime_s = (uint32_t)it->valuedouble; out->has_uptime_s = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "fw_version");
    if (cJSON_IsString(it)) { out->fw_version = it->valuestring; out->has_fw_version = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "fault_active");
    if (cJSON_IsBool(it)) { out->fault_active = cJSON_IsTrue(it); out->has_fault_active = true; }
    return true;
}

cJSON *fp_dp_report_build(const fp_dp_report_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddNumberToObject(o, "seq", (double)m->seq);
    if (m->dp) cJSON_AddItemToObject(o, "dp", cJSON_Duplicate(m->dp, 1));
    if (m->unknown) cJSON_AddItemToObject(o, "unknown", cJSON_Duplicate(m->unknown, 1));
    return o;
}

bool fp_dp_report_parse(const cJSON *root, fp_dp_report_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "seq");
    if (cJSON_IsNumber(it)) { out->seq = (uint32_t)it->valuedouble; out->has_seq = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "dp");
    if ((it != NULL)) { out->dp = (cJSON *)it; out->has_dp = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "unknown");
    if ((it != NULL)) { out->unknown = (cJSON *)it; out->has_unknown = true; }
    return true;
}

cJSON *fp_dp_read_build(const fp_dp_read_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    if (m->names) cJSON_AddItemToObject(o, "names", cJSON_Duplicate(m->names, 1));
    return o;
}

bool fp_dp_read_parse(const cJSON *root, fp_dp_read_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "names");
    if ((it != NULL)) { out->names = (cJSON *)it; out->has_names = true; } else return false;
    return true;
}

cJSON *fp_dp_write_build(const fp_dp_write_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    if (m->dp) cJSON_AddItemToObject(o, "dp", cJSON_Duplicate(m->dp, 1));
    return o;
}

bool fp_dp_write_parse(const cJSON *root, fp_dp_write_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "dp");
    if ((it != NULL)) { out->dp = (cJSON *)it; out->has_dp = true; } else return false;
    return true;
}

cJSON *fp_dp_write_result_build(const fp_dp_write_result_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddStringToObject(o, "status", m->status);
    if (m->errors) cJSON_AddItemToObject(o, "errors", cJSON_Duplicate(m->errors, 1));
    if (m->readback) cJSON_AddItemToObject(o, "readback", cJSON_Duplicate(m->readback, 1));
    return o;
}

bool fp_dp_write_result_parse(const cJSON *root, fp_dp_write_result_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "status");
    if (cJSON_IsString(it)) { out->status = it->valuestring; out->has_status = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "errors");
    if ((it != NULL)) { out->errors = (cJSON *)it; out->has_errors = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "readback");
    if ((it != NULL)) { out->readback = (cJSON *)it; out->has_readback = true; }
    return true;
}

cJSON *fp_command_build(const fp_command_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddStringToObject(o, "command", m->command);
    if (m->has_target_state) cJSON_AddStringToObject(o, "target_state", m->target_state);
    if (m->has_duration_steps) cJSON_AddNumberToObject(o, "duration_steps", (double)m->duration_steps);
    return o;
}

bool fp_command_parse(const cJSON *root, fp_command_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "command");
    if (cJSON_IsString(it)) { out->command = it->valuestring; out->has_command = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "target_state");
    if (cJSON_IsString(it)) { out->target_state = it->valuestring; out->has_target_state = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "duration_steps");
    if (cJSON_IsNumber(it)) { out->duration_steps = (uint16_t)it->valuedouble; out->has_duration_steps = true; }
    return true;
}

cJSON *fp_command_result_build(const fp_command_result_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddStringToObject(o, "command", m->command);
    cJSON_AddStringToObject(o, "status", m->status);
    if (m->has_error) cJSON_AddStringToObject(o, "error", m->error);
    if (m->has_error_detail) cJSON_AddStringToObject(o, "error_detail", m->error_detail);
    if (m->has_retry_after_s) cJSON_AddNumberToObject(o, "retry_after_s", (double)m->retry_after_s);
    if (m->readback) cJSON_AddItemToObject(o, "readback", cJSON_Duplicate(m->readback, 1));
    return o;
}

bool fp_command_result_parse(const cJSON *root, fp_command_result_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "command");
    if (cJSON_IsString(it)) { out->command = it->valuestring; out->has_command = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "status");
    if (cJSON_IsString(it)) { out->status = it->valuestring; out->has_status = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "error");
    if (cJSON_IsString(it)) { out->error = it->valuestring; out->has_error = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "error_detail");
    if (cJSON_IsString(it)) { out->error_detail = it->valuestring; out->has_error_detail = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "retry_after_s");
    if (cJSON_IsNumber(it)) { out->retry_after_s = (uint16_t)it->valuedouble; out->has_retry_after_s = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "readback");
    if ((it != NULL)) { out->readback = (cJSON *)it; out->has_readback = true; }
    return true;
}

cJSON *fp_error_report_build(const fp_error_report_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddStringToObject(o, "status", m->status);
    if (m->active_faults) cJSON_AddItemToObject(o, "active_faults", cJSON_Duplicate(m->active_faults, 1));
    if (m->log) cJSON_AddItemToObject(o, "log", cJSON_Duplicate(m->log, 1));
    return o;
}

bool fp_error_report_parse(const cJSON *root, fp_error_report_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "status");
    if (cJSON_IsString(it)) { out->status = it->valuestring; out->has_status = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "active_faults");
    if ((it != NULL)) { out->active_faults = (cJSON *)it; out->has_active_faults = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "log");
    if ((it != NULL)) { out->log = (cJSON *)it; out->has_log = true; }
    return true;
}

cJSON *fp_device_alert_build(const fp_device_alert_t *m) {
    cJSON *o = cJSON_CreateObject();
    if (!o) return NULL;
    cJSON_AddStringToObject(o, "code", m->code);
    cJSON_AddStringToObject(o, "severity", m->severity);
    if (m->has_datapoint) cJSON_AddStringToObject(o, "datapoint", m->datapoint);
    if (m->has_value) cJSON_AddNumberToObject(o, "value", (double)m->value);
    if (m->has_threshold) cJSON_AddNumberToObject(o, "threshold", (double)m->threshold);
    if (m->has_detail) cJSON_AddStringToObject(o, "detail", m->detail);
    return o;
}

bool fp_device_alert_parse(const cJSON *root, fp_device_alert_t *out) {
    memset(out, 0, sizeof(*out));
    const cJSON *it;
    it = cJSON_GetObjectItemCaseSensitive(root, "code");
    if (cJSON_IsString(it)) { out->code = it->valuestring; out->has_code = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "severity");
    if (cJSON_IsString(it)) { out->severity = it->valuestring; out->has_severity = true; } else return false;
    it = cJSON_GetObjectItemCaseSensitive(root, "datapoint");
    if (cJSON_IsString(it)) { out->datapoint = it->valuestring; out->has_datapoint = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "value");
    if (cJSON_IsNumber(it)) { out->value = (float)it->valuedouble; out->has_value = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "threshold");
    if (cJSON_IsNumber(it)) { out->threshold = (float)it->valuedouble; out->has_threshold = true; }
    it = cJSON_GetObjectItemCaseSensitive(root, "detail");
    if (cJSON_IsString(it)) { out->detail = it->valuestring; out->has_detail = true; }
    return true;
}
