/*
 * Copyright (c) 2026 Sascha G. Eurich, Melowsyne UNIPESSOAL LDA
 * SPDX-License-Identifier: MIT
 */

/* GENERATED by fountain_proto_schema/generate.py — DO NOT EDIT.
 * Source: fountain_proto_schema/schema.py */

#ifndef FOUNTAIN_MSGS_H
#define FOUNTAIN_MSGS_H

#include <stdbool.h>
#include <stdint.h>
#include "cJSON.h"

#ifdef __cplusplus
extern "C" {
#endif

#define FP_WIRE_VERSION       2
#define FP_HANDSHAKE_VERSION  1
#define FP_AUTH_SCHEME        "hmac-sha256"
#define FP_AUTH_SCOPE         "control"
#define FP_SESSION_PROOF_MSG  "ota_check"

typedef enum {
    FP_MSG_HELLO,
    FP_MSG_HELLO_ACK,
    FP_MSG_PROTOCOL_MISMATCH,
    FP_MSG_OTA_CHECK,
    FP_MSG_OTA_AVAILABLE,
    FP_MSG_OTA_NONE,
    FP_MSG_OTA_CANCEL,
    FP_MSG_OTA_STATUS,
    FP_MSG_HEARTBEAT,
    FP_MSG_DP_REPORT,
    FP_MSG_DP_READ,
    FP_MSG_DP_WRITE,
    FP_MSG_DP_WRITE_RESULT,
    FP_MSG_COMMAND,
    FP_MSG_COMMAND_RESULT,
    FP_MSG_ERROR_REPORT,
    FP_MSG_DEVICE_ALERT,
    /* Logging pull (Logging_v1.md): server reads the device's RAM ring /
     * previous-boot log; replies correlate via in_reply_to. */
    FP_MSG_LOG_READ,
    FP_MSG_LOG_BATCH,
    FP_MSG_LOG_READ_PREV,
    FP_MSG_LOG_ACK_PREV,
    FP_MSG_LOG_ACK_RESULT,
    /* Pressure history (drucksensor_datenstruktur.md): the server reads
     * back the 1-Hz sample ring (chart backfill); reply via in_reply_to.
     * Wire values 22/23 — must match fountain_proto/_messages.py. */
    FP_MSG_HISTORY_READ,
    FP_MSG_HISTORY_BATCH,
    FP_MSG_COUNT
} fp_msg_type_t;

typedef enum { FP_DIR_C2S, FP_DIR_S2C } fp_dir_t;
typedef enum { FP_AUTH_NONE, FP_AUTH_SESSION, FP_AUTH_CONTROL } fp_auth_t;

typedef struct {
    fp_msg_type_t type;
    const char   *name;
    fp_dir_t      dir;
    fp_auth_t     auth;
    uint8_t       wire;        /* Envelope version v */
    bool          is_request;  /* carries msg_id, expects a response */
    fp_msg_type_t response;    /* expected response, otherwise FP_MSG_COUNT */
} fp_msg_meta_t;

const char    *fp_msg_type_name(fp_msg_type_t t);
fp_msg_type_t  fp_msg_type_from_name(const char *name);
const fp_msg_meta_t *fp_msg_meta(fp_msg_type_t t);

/* hello (c2s, auth=none) — First message after every WS handshake; identity + negotiation. */
typedef struct {
    const char * device_id;
    bool has_device_id;
    uint8_t protocol_version;
    bool has_protocol_version;
    const char * fw_version;
    bool has_fw_version;
    const char * hw_rev;
    bool has_hw_rev;
    const char * boot_reason;
    bool has_boot_reason;
    cJSON *auth_schemes;          /* array_string; borrowed at parse */
    bool has_auth_schemes;
    cJSON *auth_kids;          /* array_string; borrowed at parse */
    bool has_auth_kids;
    const char * client_nonce;
    bool has_client_nonce;
} fp_hello_t;

cJSON *fp_hello_build(const fp_hello_t *m);
bool   fp_hello_parse(const cJSON *root, fp_hello_t *out);

/* hello_ack (s2c, auth=none) — Response to hello: acceptance, protocol/auth negotiation. */
typedef struct {
    bool accepted;
    bool has_accepted;
    cJSON *supported_protocols;          /* array_u8; borrowed at parse */
    bool has_supported_protocols;
    int64_t server_ts;
    bool has_server_ts;
    const char * reason;
    bool has_reason;
    bool auth_required;
    bool has_auth_required;
    const char * auth_scheme;
    bool has_auth_scheme;
    const char * auth_scope;
    bool has_auth_scope;
    const char * auth_kid;
    bool has_auth_kid;
    const char * server_nonce;
    bool has_server_nonce;
} fp_hello_ack_t;

cJSON *fp_hello_ack_build(const fp_hello_ack_t *m);
bool   fp_hello_ack_parse(const cJSON *root, fp_hello_ack_t *out);

/* protocol_mismatch (c2s, auth=none) — No common protocol version; the device disconnects afterwards. */
typedef struct {
    cJSON *device_protocols;          /* array_u8; borrowed at parse */
    bool has_device_protocols;
    cJSON *server_protocols;          /* array_u8; borrowed at parse */
    bool has_server_protocols;
    const char * reason;
    bool has_reason;
} fp_protocol_mismatch_t;

cJSON *fp_protocol_mismatch_build(const fp_protocol_mismatch_t *m);
bool   fp_protocol_mismatch_parse(const cJSON *root, fp_protocol_mismatch_t *out);

/* ota_check (c2s, auth=session) — One-time update query after boot; carries the session proof. */
typedef struct {
    const char * current_version;
    bool has_current_version;
    const char * hw_rev;
    bool has_hw_rev;
} fp_ota_check_t;

cJSON *fp_ota_check_build(const fp_ota_check_t *m);
bool   fp_ota_check_parse(const cJSON *root, fp_ota_check_t *out);

/* ota_available (s2c, auth=control) — Update available: URL + verification data (server-attested via MAC). */
typedef struct {
    const char * target_version;
    bool has_target_version;
    const char * url;
    bool has_url;
    uint32_t size;
    bool has_size;
    uint32_t crc32;
    bool has_crc32;
    const char * sha256;
    bool has_sha256;
    bool mandatory;
    bool has_mandatory;
    uint8_t max_attempts;
    bool has_max_attempts;
} fp_ota_available_t;

cJSON *fp_ota_available_build(const fp_ota_available_t *m);
bool   fp_ota_available_parse(const cJSON *root, fp_ota_available_t *out);

/* ota_none (s2c, auth=none) — Response to ota_check: no update. */
typedef struct {
    int _empty;  /* no body fields */
} fp_ota_none_t;

cJSON *fp_ota_none_build(const fp_ota_none_t *m);
bool   fp_ota_none_parse(const cJSON *root, fp_ota_none_t *out);

/* ota_cancel (s2c, auth=control) — Abort a running OTA. */
typedef struct {
    const char * reason;
    bool has_reason;
} fp_ota_cancel_t;

cJSON *fp_ota_cancel_build(const fp_ota_cancel_t *m);
bool   fp_ota_cancel_parse(const cJSON *root, fp_ota_cancel_t *out);

/* ota_status (c2s, auth=none) — OTA progress/result. */
typedef struct {
    const char * target_version;
    bool has_target_version;
    const char * state;
    bool has_state;
    uint8_t attempt;
    bool has_attempt;
    uint8_t progress_pct;
    bool has_progress_pct;
    const char * error;
    bool has_error;
    const char * error_detail;
    bool has_error_detail;
} fp_ota_status_t;

cJSON *fp_ota_status_build(const fp_ota_status_t *m);
bool   fp_ota_status_parse(const cJSON *root, fp_ota_status_t *out);

/* heartbeat (c2s, auth=none) — Lightweight liveness/health report. */
typedef struct {
    uint32_t uptime_s;
    bool has_uptime_s;
    const char * fw_version;
    bool has_fw_version;
    bool fault_active;
    bool has_fault_active;
} fp_heartbeat_t;

cJSON *fp_heartbeat_build(const fp_heartbeat_t *m);
bool   fp_heartbeat_parse(const cJSON *root, fp_heartbeat_t *out);

/* dp_report (c2s, auth=none) — Datapoint values (cyclic / on-change / response to dp_read). */
typedef struct {
    uint32_t seq;
    bool has_seq;
    cJSON *dp;          /* object; borrowed at parse */
    bool has_dp;
    cJSON *unknown;          /* array_string; borrowed at parse */
    bool has_unknown;
} fp_dp_report_t;

cJSON *fp_dp_report_build(const fp_dp_report_t *m);
bool   fp_dp_report_parse(const cJSON *root, fp_dp_report_t *out);

/* dp_read (s2c, auth=none) — Query datapoint values ([] = full snapshot). */
typedef struct {
    cJSON *names;          /* array_string; borrowed at parse */
    bool has_names;
} fp_dp_read_t;

cJSON *fp_dp_read_build(const fp_dp_read_t *m);
bool   fp_dp_read_parse(const cJSON *root, fp_dp_read_t *out);

/* dp_write (s2c, auth=control) — Set writable datapoints (atomic). */
typedef struct {
    cJSON *dp;          /* object; borrowed at parse */
    bool has_dp;
} fp_dp_write_t;

cJSON *fp_dp_write_build(const fp_dp_write_t *m);
bool   fp_dp_write_parse(const cJSON *root, fp_dp_write_t *out);

/* dp_write_result (c2s, auth=none) — Result of the atomic dp_write. */
typedef struct {
    const char * status;
    bool has_status;
    cJSON *errors;          /* object; borrowed at parse */
    bool has_errors;
    cJSON *readback;          /* object; borrowed at parse */
    bool has_readback;
} fp_dp_write_result_t;

cJSON *fp_dp_write_result_build(const fp_dp_write_result_t *m);
bool   fp_dp_write_result_parse(const cJSON *root, fp_dp_write_result_t *out);

/* command (s2c, auth=control) — Control action (set_state, restart, turn_on_duration, ...). */
typedef struct {
    const char * command;
    bool has_command;
    const char * target_state;
    bool has_target_state;
    uint16_t duration_steps;
    bool has_duration_steps;
} fp_command_t;

cJSON *fp_command_build(const fp_command_t *m);
bool   fp_command_parse(const cJSON *root, fp_command_t *out);

/* command_result (c2s, auth=none) — Confirmation after the target state is reached. */
typedef struct {
    const char * command;
    bool has_command;
    const char * status;
    bool has_status;
    const char * error;
    bool has_error;
    const char * error_detail;
    bool has_error_detail;
    uint16_t retry_after_s;
    bool has_retry_after_s;
    cJSON *readback;          /* object; borrowed at parse */
    bool has_readback;
} fp_command_result_t;

cJSON *fp_command_result_build(const fp_command_result_t *m);
bool   fp_command_result_parse(const cJSON *root, fp_command_result_t *out);

/* error_report (c2s, auth=none) — Full error status (response to get_error_report). */
typedef struct {
    const char * status;
    bool has_status;
    cJSON *active_faults;          /* array_object; borrowed at parse */
    bool has_active_faults;
    cJSON *log;          /* array_object; borrowed at parse */
    bool has_log;
} fp_error_report_t;

cJSON *fp_error_report_build(const fp_error_report_t *m);
bool   fp_error_report_parse(const cJSON *root, fp_error_report_t *out);

/* device_alert (c2s, auth=none) — Unsolicited alert on a new fault/critical. */
typedef struct {
    const char * code;
    bool has_code;
    const char * severity;
    bool has_severity;
    const char * datapoint;
    bool has_datapoint;
    float value;
    bool has_value;
    float threshold;
    bool has_threshold;
    const char * detail;
    bool has_detail;
} fp_device_alert_t;

cJSON *fp_device_alert_build(const fp_device_alert_t *m);
bool   fp_device_alert_parse(const cJSON *root, fp_device_alert_t *out);

#ifdef __cplusplus
}
#endif

#endif /* FOUNTAIN_MSGS_H */
