# Copyright (c) 2026 Sascha G. Eurich, Melowsyne UNIPESSOAL LDA
# SPDX-License-Identifier: MIT
#
# Pre-build: generates the build information (serienfertigung.md §14) in two
# headers under src/main/ (deliberately NOT generated/ in the root — that would
# lie outside the src glob and INCLUDE_DIRS):
#
#   build_info_gen.h         fresh on every build (a build IS a new stamp):
#       BUILD_TIMESTAMP_MS       compatibility (existing name)
#       FOUNTAINER_BUILD_VERSION from env FOUNTAINER_BUILD_VERSION, if set
#                                (release build: build_release.py pins the value
#                                ONCE per release, all devices identical),
#                                otherwise = BUILD_TIMESTAMP_MS (dev build).
#   build_info_static_gen.h  write-if-changed (no mass rebuild):
#       FOUNTAINER_FW_VERSION    from version.txt
#       FOUNTAINER_BUILD_GIT_SHA git rev-parse --short HEAD (+"-dirty")
#       FOUNTAINER_BUILD_PROFILE "production" for env esp32s3_prod, otherwise "dev"
#
# Only main.c includes build_info_gen.h — the forced recompile stays
# cheap. Both files are git-ignored.
#
# Usage:
#   PlatformIO:  extra_scripts = pre:tools/gen_build_info.py
#   standalone:  python tools/gen_build_info.py

import os
import subprocess
import time
from pathlib import Path

# SCons executes pre-scripts via exec() WITHOUT __file__ — resolve the
# project root from the PlatformIO env there, from __file__ standalone.
try:
    ROOT = Path(__file__).resolve().parent.parent
    PIOENV = os.environ.get("PIOENV", "")
except NameError:
    Import("env")  # noqa: F821  (PlatformIO SCons context)
    ROOT = Path(env["PROJECT_DIR"])  # noqa: F821
    PIOENV = env["PIOENV"]  # noqa: F821


def git_sha(root: Path) -> str:
    try:
        sha = subprocess.run(["git", "-C", str(root), "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, check=True).stdout.strip()
        dirty = subprocess.run(["git", "-C", str(root), "status", "--porcelain"],
                               capture_output=True, text=True, check=True).stdout.strip()
        return sha + ("-dirty" if dirty else "")
    except Exception:
        return "nogit"


def write_if_changed(path: Path, content: str) -> None:
    if path.exists() and path.read_text() == content:
        return
    path.write_text(content)


ms = int(time.time() * 1000)
build_version = int(os.environ.get("FOUNTAINER_BUILD_VERSION", ms))
profile = os.environ.get("FOUNTAINER_BUILD_PROFILE") or \
    ("production" if PIOENV == "esp32s3_prod" else "dev")
fw_version = (ROOT / "version.txt").read_text().strip()
sha = git_sha(ROOT)

(ROOT / "src/main/build_info_gen.h").write_text(
    "/* AUTO-GENERATED by tools/gen_build_info.py — do not edit, git-ignored. */\n"
    "#pragma once\n"
    f"#define BUILD_TIMESTAMP_MS {ms}ULL\n"
    f"#define FOUNTAINER_BUILD_VERSION {build_version}ULL\n"
)
write_if_changed(
    ROOT / "src/main/build_info_static_gen.h",
    "/* AUTO-GENERATED by tools/gen_build_info.py — do not edit, git-ignored. */\n"
    "#pragma once\n"
    f'#define FOUNTAINER_FW_VERSION    "{fw_version}"\n'
    f'#define FOUNTAINER_BUILD_GIT_SHA "{sha}"\n'
    f'#define FOUNTAINER_BUILD_PROFILE "{profile}"\n',
)
print(f"gen_build_info: build_version={build_version} fw={fw_version} git={sha} profile={profile}")
